name: 'Early Access'

on:
  push:
    branches: [ main ]

jobs:
  earlyaccess:
    name: 'Early Access'
    if: github.repository == 'redis-field-engineering/redis-cache-java' && startsWith(github.event.head_commit.message, 'Releasing version') != true
    uses: redis-field-engineering/redis-github-workflows/.github/workflows/early-access.yml@main
    with:
      jreleaser-arguments: full-release
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
      github-user: ${{ secrets.GIT_USER }}
      github-token: ${{ secrets.GIT_ACCESS_TOKEN }}
      docker-github-username: ${{ secrets.GIT_USER }}
      docker-github-password: ${{ secrets.GIT_ACCESS_TOKEN }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}